[package]
name = "rslsqp"
version = "0.1.1"
edition = "2024"
license = "BSD-3-Clause"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[features]
profiling = []
blas = []

[dependencies]
pyo3 = { version = "0.28.2", features = ["extension-module", "abi3-py39"] }
numpy = "0.28"
ndarray = "0.17"

[lints.clippy]
too_many_arguments = "allow"
needless_range_loop = "allow"
collapsible_if = "allow"
assign_op_pattern = "allow"
ptr_arg = "allow"
manual_saturating_arithmetic = "allow"
implicit_saturating_sub = "allow"
doc_overindented_list_items = "allow"
type_complexity = "allow"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
